// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kKt9r8XDi44fV54H-_6pNAUYZuZ3DHc',
    appId: '1:1098587928223:web:2025fc1baa61b6c82094aa',
    messagingSenderId: '1098587928223',
    projectId: 'craftbox-477a8',
    authDomain: 'craftbox-477a8.firebaseapp.com',
    storageBucket: 'craftbox-477a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4PwnuSIgcz_BHYXNll2iN_kvwbnEQbM',
    appId: '1:1098587928223:android:d6ec5bb2eec807042094aa',
    messagingSenderId: '1098587928223',
    projectId: 'craftbox-477a8',
    storageBucket: 'craftbox-477a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCokx4MvPHYJz1yYJIQvFwsPJwk5K55vk',
    appId: '1:1098587928223:ios:a15bf8d1a74ea6012094aa',
    messagingSenderId: '1098587928223',
    projectId: 'craftbox-477a8',
    storageBucket: 'craftbox-477a8.firebasestorage.app',
    iosBundleId: 'com.mariusioan.craftBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCokx4MvPHYJz1yYJIQvFwsPJwk5K55vk',
    appId: '1:1098587928223:ios:a15bf8d1a74ea6012094aa',
    messagingSenderId: '1098587928223',
    projectId: 'craftbox-477a8',
    storageBucket: 'craftbox-477a8.firebasestorage.app',
    iosBundleId: 'com.mariusioan.craftBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7kKt9r8XDi44fV54H-_6pNAUYZuZ3DHc',
    appId: '1:1098587928223:web:014a82c8b4424a282094aa',
    messagingSenderId: '1098587928223',
    projectId: 'craftbox-477a8',
    authDomain: 'craftbox-477a8.firebaseapp.com',
    storageBucket: 'craftbox-477a8.firebasestorage.app',
  );
}
